"use client";
import { useRef } from "react";
import type { ReportWithData } from "@/types";
import { StatCard } from "./StatCard";
import { InteractionChart, AudienceAgeChart, GenderChart } from "./ReportCharts";
import { formatNumber, formatDate } from "@/lib/utils";
import { DailySummary } from "./DailySummary";

interface Props {
  report: ReportWithData;
  isPublic?: boolean;
  dailyMetrics?: { views: number; reach: number; interactions: number; linkClicks: number; profileVisits: number; follows: number }[];
}

export function ReportView({ report, isPublic = false, dailyMetrics = [] }: Props) {
  const printRef = useRef<HTMLDivElement>(null);
  const m = report.metrics;

  async function handleExportPDF() {
    const { default: jsPDF } = await import("jspdf");
    const { default: html2canvas } = await import("html2canvas");
    if (!printRef.current) return;
    const canvas = await html2canvas(printRef.current, {
      scale: 2,
      backgroundColor: "#0a0a0f",
      useCORS: true,
    });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    let position = 0;
    const pageHeight = pdf.internal.pageSize.getHeight();
    while (position < pdfHeight) {
      pdf.addImage(imgData, "PNG", 0, -position, pdfWidth, pdfHeight);
      position += pageHeight;
      if (position < pdfHeight) pdf.addPage();
    }
    pdf.save(report.accountName + "-" + report.title + ".pdf");
  }

  const editHref = "/dashboard/reports/" + report.id + "/edit";

  return (
    <div>
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="font-display text-2xl font-bold text-white">{report.title}</h1>
          <p className="text-white/40 text-sm mt-1">
            {"@"}{report.accountName}{" · "}{formatDate(report.periodStart)}{" – "}{formatDate(report.periodEnd)}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {!isPublic && (
            <a
              href={editHref}
              className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white text-sm px-4 py-2 rounded-xl transition-all"
            >
              Edit
            </a>
          )}
          <button
            onClick={handleExportPDF}
            className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 text-white text-sm px-4 py-2 rounded-xl transition-all"
          >
            Export PDF
          </button>
        </div>
      </div>

      <div ref={printRef} className="space-y-6">
        <DailySummary dailyMetrics={dailyMetrics} />
        {isPublic && (
          <div className="glass rounded-2xl p-5 flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-orange-500 to-pink-600 flex items-center justify-center">
              <span className="text-white font-bold text-sm">GU</span>
            </div>
            <div>
              <p className="font-display font-bold text-white">Gorontalo Unite · Social Media Report</p>
              <p className="text-white/40 text-xs">Generated by Gorontalo Unite Dashboard</p>
            </div>
          </div>
        )}

        {m && (
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            <StatCard label="Total Views" value={m.views} accent="orange" />
            <StatCard label="Accounts Reached" value={m.accountsReached} accent="pink" />
            <StatCard label="Interactions" value={m.interactions} accent="blue" />
            <StatCard label="Profile Visits" value={m.profileVisits} accent="green" />
          </div>
        )}

        {m && (
          <div className="glass rounded-2xl p-6 mb-10">
            <h3 className="font-display font-semibold text-white mb-4">Detail Engagement</h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              {[
                { label: "Likes", val: m.likes },
                { label: "Comments", val: m.comments },
                { label: "Saves", val: m.saves },
                { label: "Shares", val: m.shares },
              ].map((item) => (
                <div key={item.label} className="text-center bg-white/3 rounded-xl p-4">
                  <p className="font-display text-2xl font-bold text-white">{formatNumber(item.val)}</p>
                  <p className="text-white/40 text-xs mt-1">{item.label}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {m && (
          <div className="glass rounded-2xl p-6 mb-10">
            <h3 className="font-display font-semibold text-white mb-4">Follower Growth</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="text-center bg-white/3 rounded-xl p-4">
                <p className="font-display text-2xl font-bold text-emerald-400">{"+"+formatNumber(m.followsGained)}</p>
                <p className="text-white/40 text-xs mt-1">New Follows</p>
              </div>
              <div className="text-center bg-white/3 rounded-xl p-4">
                <p className="font-display text-2xl font-bold text-white">{formatNumber(m.profileVisits)}</p>
                <p className="text-white/40 text-xs mt-1">Profile Visits</p>
              </div>
            </div>
          </div>
        )}

        {m && <InteractionChart report={report} />}

        {report.audienceData && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <AudienceAgeChart report={report} />
            <GenderChart report={report} />
          </div>
        )}

        {report.audienceData && (
          <div className="glass rounded-2xl p-6">
            <h3 className="font-display font-semibold text-white mb-4">Top Locations</h3>
            <div className="space-y-3">
              {[
                { city: report.audienceData.topCity1, pct: report.audienceData.topCity1Pct },
                { city: report.audienceData.topCity2, pct: report.audienceData.topCity2Pct },
                { city: report.audienceData.topCity3, pct: report.audienceData.topCity3Pct },
                { city: report.audienceData.topCity4, pct: report.audienceData.topCity4Pct },
                { city: report.audienceData.topCity5, pct: report.audienceData.topCity5Pct },
              ].filter((item) => item.city).map((item, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="text-white/30 text-xs w-4">{i + 1}</span>
                  <div className="flex-1">
                    <div className="flex justify-between mb-1">
                      <span className="text-white text-sm">{item.city}</span>
                      <span className="text-white/50 text-sm">{item.pct}{"%"}</span>
                    </div>
                    <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-gradient-to-r from-orange-500 to-pink-500 rounded-full"
                        style={{ width: item.pct + "%" }}
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}